Repository ProjectSWGCore/Holocore, pull requests merged in 2020-03, with the labels that each got.

#152 Fixed missing cells in multiple Dathomir patrol routes
  serverdata/nge/patrol/patrol_dathomir.sdb
  serverdata/nge/spawn/common_dathomir.sdb
Labels: enhancement

#153 Eggs for dynamic spawns
  src/main/java/com/projectswg/holocore/resources/support/data/location/ClosestLocationReducer.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DynamicSpawnLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/NoSpawnZoneLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/TerrainLevelLoader.java
  src/main/java/com/projectswg/holocore/services/support/npc/NonPlayerCharacterManager.java
  src/main/java/com/projectswg/holocore/services/support/npc/spawn/DynamicSpawnService.java
  src/test/java/com/projectswg/holocore/resources/support/data/location/TestClosestLocationReducer.java
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestDynamicSpawnLoader.java
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestNoSpawnZoneLoader.java
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestTerrainLevelLoader.java
Labels: feature

#167 Parry #67
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponType.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/weapon/TestWeaponType.java
Labels: enhancement

#166 Fixed being able to buff enemies
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuff.java
Labels: bug

#168 GCW regions determine a player inactive if player is inside a private building
  src/main/java/com/projectswg/holocore/resources/gameplay/player/ActivePlayerPredicate.java
  src/test/java/com/projectswg/holocore/resources/gameplay/player/TestActivePlayerPredicate.java
Labels: enhancement

#169 GCW ranks influence amount of points generated and increased base amo…
  src/main/java/com/projectswg/holocore/services/gameplay/gcw/CivilWarRegionService.java
Labels: enhancement

#170 Chance of rolling devastation, parry and dodge is no longer rounded down
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: bug

#171 Proper coloring in the combat log instead of always yellow (miss)
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
Labels: bug

#172 Tests of SWGBitSet#getLength and SWGBitSet#decode
  src/test/java/com/projectswg/holocore/resources/support/data/collections/TestSWGBitSet.java
Labels: enhancement

#173 Test that verifies that we can generate names for all known races
  src/main/java/com/projectswg/holocore/resources/support/data/namegen/SWGNameGenerator.java
  src/test/java/com/projectswg/holocore/resources/support/data/namegen/TestSWGNameGenerator.java
Labels: enhancement

#175 Jedi saber block chance increases parry chance
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/SkillModService.java
Labels: bug

#165 Fixed Vehicle Issues
  src/main/java/com/projectswg/holocore/services/support/objects/awareness/AwarenessService.java
Labels: bug

#190 Fix issue where you can only equip one ring
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/SWGObject.java
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGObject.java
Labels: bug

#189 Fix potential concurrent modifications in LoginService
  src/main/java/com/projectswg/holocore/services/support/global/zone/LoginService.java
Labels: bug

#188 Medic heals can freeshot
  serverdata/nge/command/special_lines.sdb
Labels: enhancement

#187 Exotic mods from equipment are granted to the player when equipped
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/SkillModService.java
Labels: bug

#185 Fix issue where aggressive NPCs teleport away from players instead of…
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
Labels: bug

#184 Fix issue where loitering NPCs inside buildings would teleport to 0 0…
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcLoiterMode.java
Labels: bug

#183 Prevent players from buffing NPCs #176
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuffNpcs.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuffPlayers.java
Labels: bug

#192 Fixed issue where static items were created with the wrong colors
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt
Labels: bug

#193 Fixed issue where you could buff invulnerable NPCs and your buff woul…
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuffNpcs.java
Labels: bug
