Repository ProjectSWGCore/Holocore, pull requests merged in 2022-07, with the labels that each got.

#572 Added support for state checks on commands
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/Command.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CreatureStateCheck.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/State.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/StateCheck.kt
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Labels: FEATURE

#573 Jedi state
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwnerNP.java
Labels: BUGFIX

#579 Added some vehicle-related system messages
  src/main/java/com/projectswg/holocore/services/gameplay/world/travel/PlayerMountService.java
Labels: IMPROVEMENT

#577 Added missing error message to SE goggle radial, guiding the player t…
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/SpecialEditionGogglesRadial.java
Labels: IMPROVEMENT

#580 Mastering a profession now gives you a badge
  src/main/java/com/projectswg/holocore/intents/gameplay/player/badge/GrantBadgeIntent.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
Labels: IMPROVEMENT

#581 Removed stat mods and remnant NPE Uniform Box code
  serverdata/player/racial_stats.sdb
  src/main/java/com/projectswg/holocore/intents/support/objects/items/OpenUniformBoxIntent.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/RadialHandler.java
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/uniform/ObjectUniformBoxRadial.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/SkillModService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/adjust/AgilityAdjustFunction.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/adjust/InnateArmorAdjustFunction.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/adjust/LuckAdjustFunction.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/adjust/PrecisionAdjustFunction.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/adjust/SingleModAdjustFunction.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/adjust/SkillModAdjust.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/adjust/StrengthAdjustFunction.java
Labels: REMOVAL

#582 Removed unreferenced SetBonusService
  src/main/java/com/projectswg/holocore/services/support/objects/items/SetBonusService.java
Labels: REMOVAL

#586 Default value for Special Attack Cost should be consistently 100 to a…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponObject.java
Labels: BUGFIX

#587 Added support for Melee Assault and Melee Strike, special attack cost…
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandService.kt
Labels: FEATURE

#588 Added support for Leg Sweep and knockdown combat abilities in general
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: FEATURE

#593 Sitting now increases HAM regeneration by 2x
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatRegenerationService.java
Labels: IMPROVEMENT

#592 Added support for Sweep Attack, which is an AoE knockdown ability
  serverdata/command/combat_commands.sdb
Labels: FEATURE

#594 Wrote a couple of automated tests for "Your modified Speed" to ensure…
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponObjectTest.java
Labels: IMPROVEMENT

#595 You must now have a supported weapon type equipped in order to execut…
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/AllLightsabersValidWeaponChecker.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/AllValidWeaponChecker.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ForcePowersValidWeaponChecker.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/MeleeValidWeaponChecker.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/RangedValidWeaponChecker.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ThrownValidWeaponChecker.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ValidWeapon.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ValidWeaponChecker.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/Command.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Labels: BUGFIX

#599 Block loot radials while the executor is dead or incapacitated
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/AIObjectRadial.java
Labels: BUGFIX

#600 Added support for Armor Break, which reduces the opponents armor prot…
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: FEATURE

#602 Filled in placeholder for visibleComponents in TangibleObject and add…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
Labels: IMPROVEMENT

#608 Fixed sometimes being stuck in combat
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatStatusService.kt
Labels: BUGFIX

#607 Server now re-uses previously generated resources instead of generati…
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/GalacticResourceSpawner.kt
Labels: BUGFIX

#609 Added support for Lunge, the range of which is 20m instead of the ran…
  serverdata/command/combat_commands.sdb
Labels: FEATURE

#610 Don't bother displaying required combat level if it's 1
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
Labels: IMPROVEMENT

#618 Fixed a couple of duel bugs
  src/main/java/com/projectswg/holocore/intents/gameplay/combat/duel/DuelPlayerIntent.java
  src/main/java/com/projectswg/holocore/resources/gameplay/combat/EnemyProcessor.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatDeathblowService.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatStatusService.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/duel/DuelService.java
  src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java
  src/main/java/com/projectswg/holocore/services/support/objects/ObjectStorageService.java
  src/test/java/com/projectswg/holocore/resources/gameplay/combat/TestEnemyProcessor.kt
Labels: BUGFIX

#623 Zabrak was missing from "rest" species restrictions, causing them to …
  src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
Labels: BUGFIX

#635 Attached species and gender restrictions to object templates instead …
  serverdata/appearance/appearance_table.sdb
  serverdata/items/items_armor.sdb
  serverdata/items/items_weapon.sdb
  serverdata/items/items_wearable.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/SpeciesRestrictionLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/TransferItemCallback.java
  src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
  src/main/java/com/projectswg/holocore/utilities/SdbGenerator.java
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TrandoshanTest.kt
  src/utility/java/com/projectswg/utility/ClientdataConvertAll.java
  src/utility/java/com/projectswg/utility/clientdata/Converters.java
Labels: BUGFIX

#633 Fixed weird buff timer behavior by reducing PLAY03 playTime delta spa…
  src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/BuffService.java
Labels: BUGFIX

#632 Fixed an issue where dynamically spawned NPCs kept respawning like st…
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/SimpleSpawnInfo.java
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/Spawner.kt
  src/main/java/com/projectswg/holocore/services/support/npc/spawn/DynamicSpawnService.java
  src/main/java/com/projectswg/holocore/services/support/npc/spawn/SpawnerService.kt
Labels: BUGFIX

#628 Rewrote SkillModService in Kotlin
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/SkillModService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/skillmod/SkillModService.kt
Labels: IMPROVEMENT

#627 stat movement no longer appears in skillmods section of the skills wi…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectClientServerNP.java
Labels: BUGFIX

#611 Fixed Defense mod behavior, so Melee Defense is your protection against melee attacks, while Unarmed Defense if your protection when you're wielding an unarmed weapon
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponType.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: BUGFIX

#637 Fixed a lot of different compiler warnings - usages of deprecated met…
  src/main/java/com/projectswg/holocore/resources/support/data/client_info/ServerFactory.java
  src/main/java/com/projectswg/holocore/resources/support/data/collections/SWGList.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/combat/FactionLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/mariadb/PswgUserDatabaseMaria.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/WaypointCmdCallback.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectSharedNP.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/group/GroupObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwnerNP.java
  src/main/java/com/projectswg/holocore/services/support/global/admin/AdminSpawnerService.kt
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGPersistence.java
Labels: IMPROVEMENT

#640 Store CREO03 variables in the base3 document, so there's less stuff d…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectShared.kt
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGPersistence.java
Labels: IMPROVEMENT

#641 Removed some unused code and files
  serverdata/player/npe_uniformbox.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/RoadmapRewardLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/items/RoadmapReward.java
Labels: REMOVAL

#636 Removed species restrictions from weapons, as no weapon is actually i…
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/TransferItemCallback.java
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TrandoshanTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipClothingTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipWeaponTest.kt
Labels: BUGFIX

#642 Created a test that verifies that health, action or mind is spent whe…
  src/test/java/com/projectswg/holocore/services/gameplay/combat/AttackCostTest.kt
Labels: IMPROVEMENT

#643 Wait synchronously after broadcasting intents, to prevent race condit…
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipClothingTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipWeaponTest.kt
Labels: IMPROVEMENT

#644 Added a couple of tests for factional PvP
  src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/DefaultWeaponFactory.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/AttackCostTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/FactionPvpTest.kt
Labels: IMPROVEMENT

#645 Added some tests that ensure armor certifications are respected
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipArmorTest.kt
Labels: IMPROVEMENT

#647 Added +10 Accuracy to the default weapon as observed in packet captur…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/DefaultWeaponFactory.kt
Labels: BUGFIX

#646 Fixed weapon range not being sent properly to the client
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponObject.java
Labels: BUGFIX

#648 Holocore-555 Remove buffs for players and vehicles in code
  serverdata/vehicles/vehicles.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/VehicleLoader.java
  src/main/java/com/projectswg/holocore/services/gameplay/world/travel/PlayerMountService.java
Labels: REMOVAL

#649 Holocore-428 [Brawler] Taunt
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDebuff.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDelayAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHitType.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandService.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/GrantLootService.java
Labels: FEATURE

#651 Holocore-650 Failed command execution should fail instead of triggeri…
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatManager.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDebuff.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDelayAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHitType.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/AttackCostTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/FactionPvpTest.kt
Labels: BUGFIX

#654 Removed an unused local variable, highestId, that was updated but nev…
  src/main/java/com/projectswg/holocore/services/support/objects/ObjectStorageService.java
Labels: IMPROVEMENT

#655 Holocore-435 [Brawler] Parry Riposte Stance
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/color/SWGColor.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/KnockdownRecoveryCmdCallback.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/KnockdownRecoveryCmdCallback.kt
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperiencePointService.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Labels: FEATURE

#656 Rewrote ActiveQuestRequirementTest so it doesn't need Mockito, as the…
  build.gradle.kts
  src/test/java/com/projectswg/holocore/resources/gameplay/conversation/requirements/ActiveQuestRequirementTest.java
Labels: IMPROVEMENT

#659 Remove unused code for old config files
  src/main/java/com/projectswg/holocore/intents/support/data/config/ConfigChangedIntent.java
  src/main/java/com/projectswg/holocore/resources/support/data/config/ConfigFile.java
Labels: REMOVAL

#662 Fixed skillpoint cap being 249 instead of 250
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
Labels: BUGFIX

#667 Improved-tests
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipArmorTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipClothingTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipLightsaberTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipWeaponTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/LightsaberInventoryTest.kt
Labels: IMPROVEMENT

#668 Holocore-568 Global cooldown should prevent ability execution
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/AttackCostTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/FactionPvpTest.kt
Labels: BUGFIX

#670 Holocore-436 [Brawler] Bleed Attack
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/State.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/BleedingCombatState.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/BlindedCombatState.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatState.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatStateService.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: FEATURE

#681 Improved API for accessing the terrain height
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/terrain/TerrainHeightLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NavigationPoint.java
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcLoiterMode.java
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
Labels: FEATURE

#685 Fixed brawler trainers sometimes being named ";" on the map
  serverdata/map/map_locations.sdb
Labels: BUGFIX

#684 Fixed utility sourceset compilation error
  src/utility/java/com/projectswg/utility/clientdata/ConvertTerrain.kt
  src/utility/java/com/projectswg/utility/clientdata/Converters.java
Labels: BUGFIX

#687 Grant Novice Entertainer upon character creation
  src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
Labels: IMPROVEMENT

#686 Holocore-683 Indoor trainers now show up correctly on planetary map (…
  src/main/java/com/projectswg/holocore/services/gameplay/world/map/MapService.java
Labels: BUGFIX

#674 Holocore-671 Previous learned and dropped ability can still be execut…
  src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/main/java/com/projectswg/holocore/services/support/global/zone/creation/CharacterCreationService.java
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipArmorTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipClothingTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipLightsaberTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/EquipWeaponTest.kt
  src/test/java/com/projectswg/holocore/resources/support/global/commands/callbacks/LightsaberInventoryTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/AbilityTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/AttackCostTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/FactionPvpTest.kt
Labels: BUGFIX

#692 Entertainers get Dancing XP by dancing
  src/main/java/com/projectswg/holocore/services/gameplay/entertainment/EntertainmentService.java
Labels: FEATURE

#695 Fixed a bug where NPCs couldn't attack
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/NpcDefaultAttackTest.kt
Labels: BUGFIX

#700 Removed unused NGE data loaders
  serverdata/skill/skill_template.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/GcwRegionLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ItemBonusSetLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/SkillTemplateLoader.java
Labels: REMOVAL

#705 Fixed a warning in SWGList
  src/main/java/com/projectswg/holocore/resources/support/data/collections/SWGList.kt
Labels: IMPROVEMENT

#720 Content update
  serverdata/npc/npc_3.sdb
  serverdata/npc/npc_4.sdb
  serverdata/npc/npc_5.sdb
  serverdata/spawn/common_dantooine.sdb
  serverdata/spawn/common_mustafar.sdb
  serverdata/spawn/dynamic/dynamic_spawns.sdb
  serverdata/static/spawns.sdb
Labels: NPC / SPAWN

#724 Fixed Holocore-723: "Teleporting/travel while mounted causing problems"
  src/main/java/com/projectswg/holocore/services/gameplay/world/travel/PlayerMountService.java
  src/test/java/com/projectswg/holocore/services/gameplay/world/travel/TestPlayerMountService.java
  src/test/java/com/projectswg/holocore/services/gameplay/world/travel/TestPlayerMountService.kt
Labels: BUGFIX

#726 Fixed Holocore-725 "No ticket selected error"
  src/main/java/com/projectswg/holocore/services/gameplay/world/travel/TravelService.java
Labels: BUGFIX

#727 Fixed Holocore-666 "AFK not showing"
  src/main/java/com/projectswg/holocore/resources/support/data/collections/SWGFlag.java
  src/main/java/com/projectswg/holocore/resources/support/global/player/PlayerFlags.java
Labels: BUGFIX
