Repository ProjectSWGCore/Holocore, pull requests merged in 2022-04, with the labels that each got.

#419 Credit option for blue frog that gives the player money for training,…
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
Labels: enhancement

#414 Fix loot radials appearing twice
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/AIObjectRadial.java
  src/test/java/com/projectswg/holocore/services/support/objects/radials/TestRadialService.java
Labels: bug

#421 Combat level is now a reflection of trained skills instead of accumul…
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatXpMultiplierLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/PlayerLevelLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/CombatLevel.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/CombatLevelCalculator.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/CombatLevelRepository.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/CombatXpCalculator.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/CombatXpMultiplierRepository.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/Experience.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperienceLevelService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperienceManager.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperiencePointService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/HealthAddedCalculator.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/SdbCombatLevelRepository.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/SdbCombatXpMultiplierRepository.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/CombatLevelCalculatorTest.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/CombatXpCalculatorTest.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/FakeCombatLevelRepository.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/FakeCombatXpMultiplierRepository.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/HealthAddedCalculatorTest.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/SdbCombatLevelRepositoryTest.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/SdbCombatXpMultiplierRepositoryTest.java
Labels: enhancement

#425 Removed Restuss from the restricted PVP Zone.
  serverdata/gcw/pvp_zones.sdb
Labels: enhancement

#489 CU uses percentages for action and mind, so let's just set the attrib…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectSharedNP.java
Labels: enhancement

#488 Fixed behavior where client never dequeued successful commands, becau…
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Labels: enhancement

#486 Fixed double loot radial bug #420
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/AIObjectRadial.java
  src/test/java/com/projectswg/holocore/services/support/objects/radials/TestRadialService.java
Labels: enhancement

#485 Fixed a couple of broken item attributes #478
  serverdata/items/items_armor.sdb
  serverdata/items/items_weapon.sdb
  serverdata/items/items_wearable.sdb
  src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
Labels: enhancement

#483 Fixed bug with 'Set name' on containers not doing anything #482
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/ContainerObjectRadial.java
Labels: enhancement

#480 Removed unused versioning #479
  src/main/java/com/projectswg/holocore/ProjectSWG.java
  src/main/java/com/projectswg/holocore/services/support/global/zone/ZoneService.java
Labels: enhancement

#427 Allow players to get to safety after being incapacitated, to prevent …
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/IncapSafetyTimer.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatDeathblowService.java
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/custom/IncapSafetyTimerTest.java
Labels: enhancement

#481 Fixed Combat XP gain being too high and reduced spammyness of "XP gai…
  src/main/java/com/projectswg/holocore/intents/gameplay/player/experience/ExperienceIntent.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
  src/main/java/com/projectswg/holocore/services/gameplay/entertainment/EntertainmentService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperiencePointService.java
Labels: enhancement

#493 Readme: Removed unnecessary steps, removed duplicate information
  README.md
Labels: IMPROVEMENT

#492 CU client isn't as intelligent as the NGE client, so it'll let player…
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
Labels: IMPROVEMENT

#499 Changed movement to Pre-NGE variant
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectClientServerNP.java
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGPersistence.java
Labels: BUGFIX

#505 Removed some NGE combat logic that would sometimes cause server error…
  serverdata/command/special_lines.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/SpecialLineLoader.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandService.kt
Labels: BUGFIX

#506 Removed a Gradle task that created a shadow jar for code that was rem…
  build.gradle.kts
Labels: REMOVAL
