Repository ProjectSWGCore/Holocore, pull requests merged in 2022-06, with the labels that each got.

#534 Update static_city_points.sdf
  serverdata/map/static_city_points.sdf
Labels: BUGFIX

#537 Added possibility of being knocked down and added an option for it at…
  src/main/java/com/projectswg/holocore/intents/gameplay/combat/CombatIntents.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/Command.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/Locomotion.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatKnockdownService.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatManager.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CheckCommandResult.kt
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Labels: FEATURE

#539 Fixed invalid combat command warnings during startup
  serverdata/command/combat_commands.sdb
Labels: BUGFIX

#543 Security check on setcurrentskilltitle command, so a player must actu…
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
Labels: BUGFIX

#544 Removed NGE style item powerups
  src/main/java/com/projectswg/holocore/intents/gameplay/combat/buffs/PowerupIntent.java
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/RadialHandler.java
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/object/PowerupRadial.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatManager.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/PowerupService.java
Labels: REMOVAL

#546 Display ? and ! above NPCs
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
Labels: FEATURE

#551 Slower HAM regeneration to prevent getting back up from incapacitatio…
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatRegenerationService.java
Labels: BUGFIX

#549 Optimized performance by stopping AI for combat NPCs once they're dead
  src/main/java/com/projectswg/holocore/resources/support/npc/ai/NpcCombatMode.kt
Labels: IMPROVEMENT

#538 Added support for more locomotions to prevent a lot of game-breaking …
  src/main/java/com/projectswg/holocore/resources/support/global/commands/Locomotion.kt
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Labels: BUGFIX

#536 Adjusted the default weapon, so it has pre-NGE stats instead of post-…
  src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
Labels: BUGFIX

#535 Unarmed Damage now increases the base damage done by the player, e.g.…
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
Labels: FEATURE

#552 We should apply the accuracy bonus to the WeaponObject and remember i…
  src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponObject.java
Labels: BUGFIX

#554 Added support for accuracy and defense skillmods, making it possible …
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/Locomotion.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/LocomotionCheck.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/MovementLocomotionCheck.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/PostureLocomotionCheck.kt
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponClass.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponType.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/weapon/TestWeaponType.java
Labels: FEATURE

#556 System messages for granted static items instead of the NGE loot box …
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/RareLootService.java
  src/main/java/com/projectswg/holocore/services/support/objects/items/StaticItemService.kt
Labels: IMPROVEMENT

#557 Modifying the customization variables of an item should notify the cl…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
Labels: BUGFIX
