Repository ProjectSWGCore/Holocore, pull requests merged in 2022-08, with the labels that each got.

#729 Content Update
  serverdata/items/items_item.sdb
  serverdata/npc/npc_3.sdb
  serverdata/spawn/dynamic/dynamic_spawns.sdb
Labels: NPC / SPAWN

#732 XP flytext not showing the multiplied XP correctly
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperiencePointService.java
Labels: BUGFIX

#733 StandardLog in ExperiencePointService
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/ExperiencePointService.java
Labels: IMPROVEMENT

#735 Armor Break should also affect innate armor
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: BUGFIX

#737 Allow Force Powers to be used
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ForcePowersValidWeaponChecker.kt
Labels: IMPROVEMENT

#741 Decouple CombatCommand from Command, so we can support Improved and A…
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DataLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandBuff.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDebuff.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDelayAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHitType.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuffNpcs.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandBuffPlayers.java
Labels: IMPROVEMENT

#742 Support for Improved and Advanced versions of abilities
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoader.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoaderTest.kt
Labels: IMPROVEMENT

#743 [Combat] Improper Experience Type
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
Labels: BUGFIX

#744 Remove defunct gcw subcommand from the QA tool
  src/main/java/com/projectswg/holocore/intents/gameplay/gcw/faction/CivilWarPointIntent.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/qatool/CmdQaTool.java
Labels: REMOVAL

#745 [Combat] Failed attacks shouldn't consume HAM
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt
Labels: BUGFIX

#746 Invulnerable faction NPCs trigger the "?"
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/custom/AIObject.java
Labels: BUGFIX

#748 Fixed invalid JSON in the readme
  README.md
Labels: BUGFIX
