Repository ProjectSWGCore/Holocore, pull requests merged in 2022-12, with the labels that each got.

#907 #893 bugfix: fixed escaping from enemy spams error
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
Labels: BUGFIX

#920 Fixed animation for Teras Kasi Combo Attack
  serverdata/command/combat_commands.sdb
Labels: BUGFIX

#921 Added animation for Teras Kasi ability 'Meditate'
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/CmdMeditate.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/StandCmdCallback.java
  src/main/java/com/projectswg/holocore/services/gameplay/entertainment/EntertainmentService.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
Labels: FEATURE, COMMAND

#918 Added support for displaying effects on affected targets and support …
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
Labels: FEATURE

#926 Tweaked Bacta Shot, so it's action and mind consumption are higher an…
  serverdata/command/combat_commands.sdb
Labels: IMPROVEMENT

#935 Tweaked how Accuracy and Defense modifiers influence combat
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: IMPROVEMENT

#925 Healing Efficiency now increases damage healed as a percentage
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
Labels: IMPROVEMENT

#936 Added animation for Bacta Shot and other commands
  serverdata/command/combat_commands.sdb
  serverdata/items/items_armor.sdb
  serverdata/npc/npc_stats.sdb
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java
Labels: IMPROVEMENT, BUGFIX

#937 Wrote regression test for a bug with Healing Efficiency, where it cou…
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHealTest.kt
Labels: IMPROVEMENT

#1155 Commands for medic / doctor / combat medic
  serverdata/command/combat_commands.sdb
Labels: COMMAND
