Repository ProjectSWGCore/Holocore, pull requests merged in 2023-10, with the labels that each got.

#1373 Harvesting creatures grants Scouting Experience
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/storage/GalacticResourceContainer.kt
  src/main/java/com/projectswg/holocore/services/gameplay/crafting/resource/CreatureHarvestingService.kt
  src/main/java/com/projectswg/holocore/services/gameplay/crafting/resource/ResourceService.java
  src/test/java/com/projectswg/holocore/services/gameplay/crafting/resource/CreatureHarvestingTest.kt
Labels: FEATURE, BUGFIX

#1377 abandonQuest
  serverdata/command/commands_global.sdb
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoaderTest.kt
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/CommandLoaderTest.kt
Labels: IMPROVEMENT

#1407 Update CombatExperienceService.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
Labels: IMPROVEMENT

#1384 Fixed client crash when being granted a quest #1383
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwner.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/Quest.kt
  src/test/java/com/projectswg/holocore/resources/gameplay/conversation/requirements/QuestSerializationTest.kt
Labels: BUGFIX
