Repository ProjectSWGCore/Holocore, pull requests merged in 2023-12, with the labels that each got.

#1432 Load in additional NPC equipment
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/NpcEquipmentLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/npc/NpcStaticSpawnLoader.java
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/SimpleSpawnInfo.java
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/SpawnInfo.java
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/Spawner.kt
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/NpcEquipmentLoaderTest.kt
Labels: IMPROVEMENT

#1429 [Quest] Support comm messages without a NPC
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/quest/QuestTaskTypeTest.kt
Labels: BUGFIX

#1443 Integration test superclass
  src/test/java/com/projectswg/holocore/headless/grouping.kt
  src/test/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreationTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/TipCreditsTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/SkillTreeTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/group/GroupTest.kt
  src/test/java/com/projectswg/holocore/services/support/CharacterManagementTest.kt
  src/test/java/com/projectswg/holocore/services/support/KillAdminCommandTest.kt
  src/test/java/com/projectswg/holocore/services/support/LoginTest.kt
  src/test/java/com/projectswg/holocore/test/runners/IntegrationTest.kt
Labels: IMPROVEMENT

#1453 Content update
  serverdata/buildout/buildout_atmosphere.sdb
  serverdata/conversation/questgiver.sdb
  serverdata/conversation/questgiver/already_completed.json
  serverdata/conversation/questgiver/default.json
  serverdata/conversation/questgiver/kill_banthas.json
  serverdata/conversation/spawn_conversation_map.msdb
  serverdata/loot/loot_table.sdb
  serverdata/spawn/common_tatooine.sdb
  serverdata/spawn/dynamic/dynamic_spawns.sdb
Labels: CONTENT

#1449 Testcases for Trapping XP
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandDelayAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHandler.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/Die.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/RandomDie.kt
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/test/java/com/projectswg/holocore/headless/combat.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/command/TestCombatCommandAttack.java
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/TrappingXPTest.kt
  src/test/java/com/projectswg/holocore/test/runners/DeterministicDie.kt
  src/test/java/com/projectswg/holocore/test/runners/IntegrationTest.kt
Labels: IMPROVEMENT

#1456 Content update
  serverdata/items/items_armor.sdb
  serverdata/items/items_item.sdb
  serverdata/items/items_wearable.sdb
  serverdata/items/master_item.msdb
  serverdata/loot/loot_table.sdb
  serverdata/npc/npc_2.sdb
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatNpcService.java
Labels: CONTENT

#1458 [Quest] Converted QuestService to Kotlin
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: IMPROVEMENT

#1462 Updated loot table
  serverdata/loot/loot_table.sdb
Labels: CONTENT

#1461 quest.task.ground.nothing
  src/main/java/com/projectswg/holocore/intents/gameplay/player/quest/QuestIntents.kt
  src/main/java/com/projectswg/holocore/resources/gameplay/conversation/events/AdvanceQuestEvent.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/ConversationLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/conversation/events/AdvanceQuestEventParser.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/quest/QuestTaskTypeTest.kt
Labels: FEATURE

#1463 Renamed IntegrationTest to AcceptanceTest
  src/test/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreationTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/loot/LootTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/TipCreditsTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/AdminCommandAccessTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/SkillTreeTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/experience/TrappingXPTest.kt
  src/test/java/com/projectswg/holocore/services/gameplay/player/group/GroupTest.kt
  src/test/java/com/projectswg/holocore/services/support/CharacterManagementTest.kt
  src/test/java/com/projectswg/holocore/services/support/KillAdminCommandTest.kt
  src/test/java/com/projectswg/holocore/services/support/LoginTest.kt
  src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt
Labels: IMPROVEMENT

#1470 Content update
  serverdata/conversation/mensix_mce_hunt.sdb
  serverdata/conversation/mensix_mce_hunt/default.json
  serverdata/conversation/mensix_mce_hunt/kill_blistmok.json
  serverdata/conversation/mensix_mce_hunt/kill_jundak.json
  serverdata/conversation/mensix_mce_hunt/kill_lava_beetle.json
  serverdata/conversation/mensix_mce_hunt/kill_tanray.json
  serverdata/conversation/mensix_mce_hunt/kill_tulrus.json
  serverdata/conversation/mensix_mce_hunt/kill_xandank.json
  serverdata/conversation/spawn_conversation_map.msdb
  serverdata/faction/faction_datatable.sdb
  serverdata/items/items_weapon_cu.sdb
  serverdata/npc/npc_1.sdb
  serverdata/npc/npc_2.sdb
  serverdata/npc/npc_5.sdb
  serverdata/patrol/patrol_mustafar.sdb
  serverdata/spawn/common_mustafar.sdb
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
Labels: IMPROVEMENT, CONTENT

#1466 Removed TODO for a NGE feature in quests
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: REMOVAL

#1471 [NPC] NPCs that initially spawn together now also respawn together
  src/main/java/com/projectswg/holocore/services/support/npc/spawn/SpawnerService.kt
Labels: IMPROVEMENT

#1474 Replaced two usages of a deprecated Gradle API
  build.gradle.kts
Labels: IMPROVEMENT

#1473 Reduced flakiness of GroupTest
  build.gradle.kts
  src/test/java/com/projectswg/holocore/headless/grouping.kt
  src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java
Labels: IMPROVEMENT

#1472 Specified JDK distribution parameter, so actions/setup-java can be bumped
  .github/workflows/verify.yml
Labels: BUGFIX

#1476 [Quest] Play music on quest task activation and completion
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: FEATURE

#1479 Improved Gradle 9.x compatibility
  build.gradle.kts
Labels: IMPROVEMENT

#1480 Content update
  serverdata/items/items_weapon_cu.sdb
  serverdata/patrol/patrol_mustafar.sdb
  serverdata/spawn/common_mustafar.sdb
Labels: CONTENT

#1481 Content update
  serverdata/items/items_weapon_cu.sdb
Labels: BUGFIX

#1484 Log PvE kills
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatDeathblowService.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatDeathblowService.kt
Labels: IMPROVEMENT

#1485 Patch CVE-2023-42503 (minor security vulnerability)
  build.gradle.kts
Labels: IMPROVEMENT
