Repository ProjectSWGCore/Holocore, pull requests merged in 2023-01, with the labels that each got.

#1158 Use pre-NGE weapon type for heavy weapons, allowing the client to dis…
  serverdata/command/combat_commands.sdb
  serverdata/items/items_weapon.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/weapon/WeaponType.java
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/weapon/TestWeaponType.java
Labels: BUGFIX

#1162 Updated to proper CU values in combat command / player levels / weapon database
  serverdata/command/combat_commands.sdb
  serverdata/items/items_weapon_cu.sdb
  serverdata/items/master_item.msdb
  serverdata/player/player_levels_cu.sdb
Labels: IMPROVEMENT

#1163 Cleaned up CombatCommandAttack by removing some unused features and T…
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: IMPROVEMENT

#1164 Added more CU weapons to the database (LS / Mustafar / Grenades)
  serverdata/items/items_weapon_cu.sdb
Labels: IMPROVEMENT

#1165 Added missing animations to all the lightsaber attacks
  serverdata/command/combat_commands.sdb
Labels: BUGFIX

#1166 Spray Shot is now a cone instead of an area attack and the animation is now firing in a cone
  serverdata/command/combat_commands.sdb
Labels: BUGFIX

#1167 Combat abilities can now target a specific part of the body of an enemy
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/CombatCommandLoader.java
  src/main/java/com/projectswg/holocore/resources/support/global/commands/CombatCommand.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
Labels: IMPROVEMENT

#1168 Added Master Medic / Master Doctor / Master Combat Medic and Force Se…
  serverdata/command/combat_commands.sdb
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
Labels: IMPROVEMENT

#1171 Removed some dead code
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/database/Database.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/database/PswgGcwRegionDatabase.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/mongodb/PswgDatabase.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/mongodb/PswgGcwRegionDatabaseMongo.kt
Labels: REMOVAL

#1172 Removed structure deeds from CBT
  serverdata/spawn/dynamic/dynamic_lairs.sdb
  serverdata/spawn/dynamic/dynamic_scenes.sdb
  serverdata/spawn/dynamic/dynamic_spawns.sdb
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
Labels: IMPROVEMENT
