Repository ProjectSWGCore/Holocore, pull requests merged in 2023-04, with the labels that each got.

#1198 Fixed issue where some looted items had "Volume: 0" when examining them
  src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/generation/ItemLootGenerator.kt
Labels: BUGFIX

#1199 Fixed a couple of bugs in command requirements, where they only affec…
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
Labels: BUGFIX

#1196 Fixed being unable to use survey tools, caused by server reboots
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/GalacticResource.java
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/GalacticResourceSpawner.kt
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/raw/RawResourceLoader.java
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/survey/SampleLoopSession.java
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/survey/SurveyHandler.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/services/gameplay/crafting/resource/ResourceService.java
  src/test/java/com/projectswg/holocore/resources/gameplay/crafting/resource/raw/TestRawResourceLoader.java
Labels: BUGFIX

#1204 Fixed a bug where the starter clothing had 0 volume when examining th…
  src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
Labels: BUGFIX

#1201 Fixed code inspection warnings in the SWG name generator and fixed a …
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/resource/galactic/GalacticResourceSpawner.kt
  src/main/java/com/projectswg/holocore/resources/support/data/namegen/RaceNameRule.java
  src/main/java/com/projectswg/holocore/resources/support/data/namegen/SWGNameGenerator.java
  src/main/java/com/projectswg/holocore/services/support/global/zone/creation/CharacterCreationService.java
  src/test/java/com/projectswg/holocore/resources/support/data/namegen/TestSWGNameGenerator.java
Labels: IMPROVEMENT

#1200 Sampled resources are now added to an existing stack in the inventory…
  src/main/java/com/projectswg/holocore/resources/gameplay/crafting/survey/SampleLoopSession.java
Labels: BUGFIX

#1209 [General] Fixed a bug where you had to relog to see new names for way…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwner.java
Labels: BUGFIX, COMMAND

#1216 [Combat] Combat and the Combat Level - lowering/increasing XP
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
Labels: BUGFIX

#1215 Slitherhorn has 0 volume
  src/main/java/com/projectswg/holocore/resources/support/global/zone/creation/CharacterCreation.java
Labels: BUGFIX

#1235 The log statement has a bug with the "Expected" part, where it displa…
  src/main/java/com/projectswg/holocore/resources/support/global/network/NetworkClient.kt
Labels: BUGFIX

#1242 [Mission] System message no longer says you have earned 0 credits for…
  src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionService.kt
Labels: BUGFIX

#1245 [Combat] Ability to damage lairs
  src/main/java/com/projectswg/holocore/intents/gameplay/combat/CombatIntents.kt
  src/main/java/com/projectswg/holocore/resources/gameplay/combat/EnemyProcessor.kt
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdServer.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectAwareness.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatRegenerationService.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatStatusService.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.java
  src/main/java/com/projectswg/holocore/services/gameplay/conversation/ConversationService.java
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandQueueService.java
  src/main/java/com/projectswg/holocore/services/support/npc/ai/AIService.java
  src/test/java/com/projectswg/holocore/services/gameplay/combat/LairAttackTest.kt
Labels: FEATURE

#1247 [Mission] Vehicles in the datapad no longer count towards the cap of …
  src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionService.kt
Labels: BUGFIX

#1285 [Misc] Fix being unable to set title back to No Title
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.java
Labels: BUGFIX

#1281 [Misc] Optimize memory usage of CombatExperienceService
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
Labels: BUGFIX

#1269 [Faction] Switching factions resets your faction rank
  src/main/java/com/projectswg/holocore/services/gameplay/faction/FactionFlagService.java
Labels: FEATURE

#1268 Colored logs in development mode
  .idea/runConfigurations/Start_server__development_.xml
Labels: IMPROVEMENT

#1283 [Mission] Terminal missions spawn lairs
  src/main/java/com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java
  src/main/java/com/projectswg/holocore/services/gameplay/missions/DestroyMissionService.kt
  src/main/java/com/projectswg/holocore/services/support/npc/spawn/SpawnerService.kt
  src/test/java/com/projectswg/holocore/services/gameplay/combat/NpcDefaultAttackTest.kt
Labels: FEATURE

#1292 Changed the size of some creatures that were too tall/big
  serverdata/npc/npc_2.sdb
Labels: NPC / SPAWN

#1295 Updated content
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
Labels: IMPROVEMENT

#1297 Removed NGE TANO06 parser, as TANO06 doesn't override anything from t…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/tangible/TangibleObject.java
Labels: REMOVAL

#1300 [Admin] Admins can more easily test factions with the /setFaction com…
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/admin/CmdSetFaction.kt
  src/main/java/com/projectswg/holocore/services/support/global/commands/CommandExecutionService.java
Labels: IMPROVEMENT

#1309 [Misc] Parsing of explorationBadges.sdb is now in a DataLoader, using…
  serverdata/badges/explorationBadges.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ExplorationBadgeLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/badge/ExplorationBadgeService.kt
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/ExplorationBadgeLoaderTest.kt
Labels: IMPROVEMENT

#1311 [Misc] Converted GuildService to Kotlin
  src/main/java/com/projectswg/holocore/services/gameplay/player/guild/GuildService.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/guild/GuildService.kt
Labels: IMPROVEMENT

#1312 [Misc] Updated Kotlin to 1.8.21 from 1.7.10
  .idea/kotlinc.xml
  build.gradle.kts
Labels: IMPROVEMENT

#1313 [Misc] CombatExperienceService uses the NpcStat DataLoader instead of…
  src/main/java/com/projectswg/holocore/services/gameplay/combat/CombatExperienceService.java
Labels: IMPROVEMENT
