Repository ProjectSWGCore/Holocore, pull requests merged in 2024-07, with the labels that each got.

#1569 Combat engine now takes accuracy bonus from buffs into account
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandAttack.kt
Labels: FEATURE

#1570 Take health wounds into account when using a healing ability
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.kt
Labels: IMPROVEMENT

#1581 Content Update
  serverdata/conversation/cybernetics.sdb
  serverdata/conversation/cybernetics/install.json
  serverdata/conversation/cybernetics/remove.json
  serverdata/conversation/cybernetics/repair.json
  serverdata/conversation/cybernetics/start.json
  serverdata/conversation/spawn_conversation_map.msdb
  serverdata/spawn/common_corellia.sdb
  serverdata/spawn/common_naboo.sdb
  serverdata/spawn/common_tatooine.sdb
  serverdata/spawn/instance_kashyyyk_myyydril.sdb
Labels: CONTENT

#1579 Fixed wrong container error message being used for ContainerResult.SL…
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/TransferItemCallback.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/loot/GrantLootService.java
Labels: BUGFIX

#1585 Fixed infinite duration buffs expiring immediately
  src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/BuffService.kt
Labels: BUGFIX

#1582 Generalized copyright headers added to source code files a bit, so th…
  .idea/copyright/Holocore.xml
  .idea/copyright/PSWGCommon.xml
Labels: DOCUMENTATION

#1584 Fixed mongo-express health check, where "localhost" could no longer b…
  docker-compose.yml
Labels: BUGFIX

#1574 Fixed a NullPointerException when displaying SUI message boxes
  src/main/java/com/projectswg/holocore/resources/support/global/zone/sui/SuiMessageBox.kt
  src/main/java/com/projectswg/holocore/services/support/global/zone/LoginService.java
  src/test/java/com/projectswg/holocore/test/resources/GenericPlayer.java
  src/test/java/com/projectswg/holocore/test/runners/AcceptanceTest.kt
Labels: BUGFIX
