Repository ProjectSWGCore/Holocore, pull requests merged in 2024-04, with the labels that each got.

#1515 Removed unnecessary isEntertainer-check in EntertainmentService
  src/main/java/com/projectswg/holocore/services/gameplay/entertainment/EntertainmentService.kt
Labels: IMPROVEMENT

#1517 Simplify loading of tasks in QuestLoader
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
Labels: IMPROVEMENT

#1518 Removed unnecessary inheritance of StartDanceCallback in PlaceStructureCmdCallback
  src/main/java/com/projectswg/holocore/resources/support/global/commands/callbacks/PlaceStructureCmdCallback.kt
Labels: IMPROVEMENT

#1520 Content update
  serverdata/items/items_armor.sdb
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/terminal/TerminalCharacterBuilderRadial.java
Labels: CONTENT

#1519 Removed some unused methods from Player, where other equivalents have…
  src/main/java/com/projectswg/holocore/resources/support/global/player/Player.java
Labels: IMPROVEMENT

#1527 When generating a name for a given Race, don't bother checking if the…
  src/main/java/com/projectswg/holocore/resources/support/data/namegen/SWGNameGenerator.java
Labels: IMPROVEMENT

#1526 Removed placeholder classes for NGE static item types
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/StaticItemLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/StaticItemCreator.kt
Labels: REMOVAL

#1525 Removed unused class RadialTemplate
  src/main/java/com/projectswg/holocore/resources/support/objects/radial/RadialTemplate.java
Labels: IMPROVEMENT

#1524 Removed an unused way of setting the born date of a character
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectShared.kt
  src/main/java/com/projectswg/holocore/utilities/MathUtils.java
Labels: IMPROVEMENT

#1523 Draft schematic group loader
  serverdata/crafting/schematic_group.sdb
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/SchematicGroupLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/SchematicGroupLoaderTest.kt
  src/utility/java/com/projectswg/utility/ClientdataConvertAll.java
  src/utility/java/com/projectswg/utility/clientdata/Converters.java
Labels: FEATURE

#1522 Fixed draft schematic persistence problem, where a server reboot woul…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwnerNP.kt
Labels: BUGFIX
