Repository ProjectSWGCore/Holocore, pull requests merged in 2024-06, with the labels that each got.

#1538 Content Update
  serverdata/buildout/buildout_atmosphere.sdb
  serverdata/buildout/buildout_camps.sdb
  serverdata/buildout/buildout_cloning.sdb
  serverdata/buildout/buildout_common.sdb
  serverdata/buildout/buildout_instance_droid_army.sdb
  serverdata/buildout/buildout_invasion_gcw_bestine.sdb
  serverdata/npc/npc_4.sdb
  serverdata/spawn/common_tatooine.sdb
  serverdata/spawn/instance_kashyyyk_avatar_easy.sdb
  serverdata/spawn/instance_kashyyyk_avatar_hard.sdb
  serverdata/spawn/instance_kashyyyk_avatar_medium.sdb
  serverdata/spawn/instance_mustafar_orf.sdb
  serverdata/spawn/invasion_droid_army.sdb
  serverdata/weather/weather.sdb
Labels: CONTENT

#1536 Mark Player as @NotNull in PlayerEventIntent to communicate null chec…
  src/main/java/com/projectswg/holocore/intents/support/global/zone/PlayerEventIntent.java
Labels: IMPROVEMENT

#1537 BuffService refactor
  src/main/java/com/projectswg/holocore/intents/gameplay/combat/buffs/BuffIntent.java
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/BuffLoader.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/Buff.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectSharedNP.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/BuffService.java
  src/main/java/com/projectswg/holocore/services/gameplay/combat/buffs/BuffService.kt
  src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandCommon.java
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGPersistence.java
Labels: IMPROVEMENT, BUGFIX

#1539 Skip unsupported quest task types and let the player know what happened
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: FEATURE

#1532 Grant draft schematics from skills
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObject.kt
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/player/PlayerObjectOwnerNP.kt
  src/main/java/com/projectswg/holocore/services/gameplay/player/experience/skills/SkillService.kt
Labels: FEATURE

#1533 DraftSchematicLoader that parses all the json files under server_data…
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/DraftSchematicLoader.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/ServerData.kt
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/DraftSchematicLoaderTest.kt
Labels: FEATURE

#1541 Fixed a bug with quest rewards, where completing tasks that don't gra…
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: BUGFIX

#1545 Handle unknown quests being granted in a better way than causing a Nu…
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: BUGFIX

#1544 SUI message box tasks in quest should only progress when the window i…
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: BUGFIX

#1546 Play SUI message box sounds in quests, as the NPE tutorial makes exte…
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.java
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: FEATURE

#1552 Fixed instancing feature in awareness, so we can use it for the NPE t…
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
Labels: BUGFIX

#1553 Fixed %TT in "quest received" system message
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.kt
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestQuestLoader.java
  src/test/java/com/projectswg/holocore/resources/support/data/server_info/loader/TestQuestLoader.kt
Labels: BUGFIX

#1554 Added missing system message when completing a quest
  src/main/java/com/projectswg/holocore/intents/gameplay/player/quest/QuestIntents.kt
  src/main/java/com/projectswg/holocore/resources/support/data/server_info/loader/QuestLoader.kt
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestRetrieveItemRadialHandler.kt
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: BUGFIX

#1556 Added missing "credits transferred to your account" system message wh…
  src/main/java/com/projectswg/holocore/services/gameplay/player/quest/QuestService.kt
Labels: BUGFIX

#1558 Persist wounds, so a server reboot won't reset them
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObject.java
  src/main/java/com/projectswg/holocore/resources/support/objects/swg/creature/CreatureObjectShared.kt
  src/test/java/com/projectswg/holocore/resources/support/objects/swg/TestSWGPersistence.java
Labels: BUGFIX

#1575 Content update
  serverdata/conversation/tatooine_mos_eisley_bib_fortuna/start.json
  serverdata/conversation/tatooine_mos_eisley_cheated_gambler/hear.json
  serverdata/cybernetics/cybernetics.sdb
  serverdata/items/items_weapon_cu.sdb
  serverdata/npc/npc_2.sdb
  serverdata/spawn/common_naboo.sdb
  serverdata/spawn/common_tatooine.sdb
Labels: CONTENT
